# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edgectl < Formula
  desc "CLI for Edgeworx Cloud"
  homepage "https://cloud.edgeworx.io"
  version "0.5.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_macos_amd64.tar.gz"
      sha256 "09d4ebc030f96e5feebbeb97f449a5f8d7df250a2c4bed5dbc9e514f7ac26a0d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_macos_arm64.tar.gz"
      sha256 "a8124f4eedacfdd4392cad411bbaea046018587d580158dff1f1d337acfcc18d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_amd64.tar.gz"
      sha256 "d8a31f5cdc1167ca571d7b8d595a082136644a89b0392722c61f728d812ac9b8"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_arm.tar.gz"
      sha256 "b3ea7a0f3a3363c4dbd7c2dcf2ffebf7102a10b22d37b91c3c0cd7f55f0dd8d4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_arm64.tar.gz"
      sha256 "f75f30c864d159f9d0bafd7c65b3eeb9fac804f6f86c8db680144b4700504d54"
    end
  end

  def install
    bin.install "edgectl"
  end

  test do
    system "#{bin}/edgectl version"
  end
end
