# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edgectl < Formula
  desc "CLI for Edgeworx Cloud"
  homepage "https://cloud.edgeworx.io"
  version "0.5.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_macos_amd64.tar.gz"
      sha256 "1f5780c957602ecd146e5f531aee33cf347515a2cd7d7a07615ce6dca31717e5"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_macos_arm64.tar.gz"
      sha256 "4339ab0c0e8f44840b3bd7fea4fee01fd8eee0050da24fc392d2d791c7cabbe6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_amd64.tar.gz"
      sha256 "d58b49cf7966ebffad62ced6d56722d0231e6fcd6802ea1a2c9081cbb8c5a68a"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_arm.tar.gz"
      sha256 "e7ec3bfcabae3d460a6f3a08bf2a3f349023e900905b5a6a4326cfed9d58935c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Edgeworx/homebrew-edgectl-dev/releases/download/v0.5.1/edgectl_0.5.1_arm64.tar.gz"
      sha256 "bc1938cffae36132842f8e7218f700a7b21499affd2a180b1d3cb49549b0b450"
    end
  end

  def install
    bin.install "edgectl"
  end

  test do
    system "#{bin}/edgectl version"
  end
end
